### ISSUE TITLE
Add !raids

### ISSUE THREAD

**Issue by pjlangsam** [Professor-Redwood-Team/Professor-Redwood#1]
Save raids with an object or databsae to allow usersto see current raids in their neighborhood

**Comment by kniteshift** [comment]
@pjlangsam on it!

Going to try and save the raids in memory

**Comment by kniteshift** [comment]
Raids is ready for review in #33 
Groups is still be worked on.

Current functionality is:

1. Returns raids based on what channel the command was called on.
2. Returns raids based on what channel the command was called on and accepts a pokemon parameter for filtering.

Also it appends a unique ID to the raid for creating groups later.
