### ISSUE TITLE
Remove need to manually tag shiny pokemon

### ISSUE THREAD

**Issue by cub01d** [Professor-Redwood-Team/Professor-Redwood#105]
Since we already do a lookup on the tagged pokemon to see if there is a discord role and emoji for that pokemon (eg. `!wild pokemon` will check to see if we have a `@pokemon` role and `:pokemon:` emoji) we can probably drop support for users reporting shinycheck.

We will still have the `@shinycheck` role so users can decide if they want to get notified for potential shiny pokemon, but we should **REMOVE** the logic where the bot will search the message for anything with shiny in it, and then add in the `@shinycheck` role at the end.

For this to fully work, we need to cross check the reported `!wild pokemon` against a list of known potential shinies.

**Comment by ZVelasco** [comment]
For this to work, you have to do it for wild and quests, but you can’t do it for raids. The notifications will be overwhelming if you do it for raids. Also, another issue is it requires constant, immediate updates. The beauty about the shinycheck being to be used manually is most times, Niantic doesn’t announce if a Pokémon has become shiny in advance. The current system allows people to start using the tag the second an unannounced shiny mon is confirmed
