### ISSUE TITLE
Incorrect parsing for messages with newlines

### ISSUE THREAD

**Issue by cub01d** [Professor-Redwood-Team/Professor-Redwood#109]
Some users are issuing bot commands with newlines instead of/in addition to spaces, which is getting incorrectly parsed.

**Comment by cub01d** [comment]
change 
```
    const msglower = message.content.toLowerCase();
    const msgSplit = message.content.toLowerCase().split(' ');
```
to 
```
    const msglower = message.content.toLowerCase().replace('\n', ' ');
    const msgSplit = message.content.toLowerCase().replace('\n', ' ').split(' ');
```

in all affected files - src/chatcommands/{egg,raid,wild,quest,tr}.js

**Comment by ZVelasco** [comment]
Your fix was implemented to quest. Not on the others because it removes the first word from the new line. New line reporting is never used for the other commands so not a big deal.
