### ISSUE TITLE
Auto maps link after user declares a raid

### ISSUE THREAD

**Issue by pjlangsam** [Professor-Redwood-Team/Professor-Redwood#11]
Code https://github.com/Professor-Redwood-Team/Professor-Redwood/pull/15

Todo
- [x] Functionality @kniteshift 
- [ ] Allow for backwards compatibility if config does not specify mongo address and google api key @kniteshift 
- [x] Provide google api and mongo keys @kniteshift 
- [ ] Merge PR https://github.com/Professor-Redwood-Team/Professor-Redwood/pull/15 @stefangimmillaro
- [ ] Test and Release @stefangimmillaro @pjlangsam

**Comment by kniteshift** [comment]
@pjlangsam backwards compatibility resolved with latest commit

**Comment by kniteshift** [comment]
@pjlangsam @stefangimmillaro second item has been done on the list.
