### ISSUE TITLE
Few updates for the Professor

### ISSUE THREAD

**Issue by Alterraia** [Professor-Redwood-Team/Professor-Redwood#122]
Updated counters.json with all Pokemon from Gens 1-5 including placeholders for the known Galarian form Pokemon.  Will update when the expansions come out for Sword/Shield.

Updated cp.json with CPs for all Pokemon Gens 1-5 including alternate forms.

Updated moves.json to include current moves.  Waiting on stats for Aeroblast and Sacred Sword.

Updated pokemon.json with ALL Pokemon including ALL known forms.  Gen's 6-8 have placeholders entered with stats from PokemonGoHub.  Will update as those gens are live.

Updated string.json for perfect CP strings for levels 1-35 for all Pokemon Gens 1-5 including alternate forms.

I apparently don't know how to upload those files via this method.  Let me know and I will send them to whoever I need to.

Also, I will update counters.json when Gen 6 is live and most of the Pokemon will be updated with recommended counters that will include Gen 6.

**Comment by cub01d** [comment]
can you reach out to me on discord? trainwreck3d (valor). I'll find a way to sync the changes over to the repo.
