### ISSUE TITLE
quoted message considered for moderation

### ISSUE THREAD

**Issue by pr80ik** [Professor-Redwood-Team/Professor-Redwood#124]
When quoting a message from the bot that contains a privileged tag such as `@tier5` the bot will show rage to the poster. 

expected: quoted message should not processed by the bot.

![Screenshot_20200705-124228](https://user-images.githubusercontent.com/3183350/86545351-d4996180-bf1d-11ea-90dd-90171b141a45.png)

**Comment by pr80ik** [comment]
#125

**Comment by cub01d** [comment]
This seems like expected behavior - if you quote a message with tags in it, your message will also notify the roles tagged. The discord server has tagging special roles disabled like `@tier5` but this looks like another way to get around it. I'll be closing this as won't fix.
