### ISSUE TITLE
setup roles and channels automatically based on config

### ISSUE THREAD

**Issue by stefangimmillaro** [Professor-Redwood-Team/Professor-Redwood#23]

**Comment by fmoo** [comment]
Would this (creating new roles) require the initial role for professor redwood to include "Manage Server"?

**Comment by pjlangsam** [comment]
No, only you and your most trusted human members should ever have that
permission. Redwood does not need that. Creating roles can be done with the
manage roles permission. Hope that helps!

**Comment by stefangimmillaro** [comment]
Thank you for taking this up! I'll be reviewing in the next day.

**Comment by fmoo** [comment]
No problem; I was setting up my own instance and setting up all the roles was too much work. 

The biggest missing piece right now is I can't create the neighborhood channels automatically - if you add the Region -> Neighborhood[] mappings to constants.js, that would help a ton.
