### ISSUE TITLE
Automated Messaging for Team Assignments

### ISSUE THREAD

**Issue by mralanlee** [Professor-Redwood-Team/Professor-Redwood#36]
Instead of having users go into a channel to assign a team via command, could unassigned users be automated a one time message? 

Case:

- If a new user joins, automatically receive a message about assignment via DM
- If an existing user is unassigned, DM user about team assignments.

Pitfalls: 
- Every time we refresh the bot, all unassigned users will get a DM. However, we only really restart the bot to push new features.

Thoughts?

I can take this on after #33

**Comment by pjlangsam** [comment]
There must be an event that fires on client having a user join... That
would be easier I think. We can have the bot mention them in the red wood
channel and ask what team they're on and walk them thru setup

**Comment by flippinjoe** [comment]
I actually have a version of this which DMs the user on join, and within that dm the user can set their team and region.  It also goes through this DM logic anytime an un-assigned user posts a message in any channel.  The last bit is somewhat overkill, but it gets the point across and removes some of the user setup confusion from the professor channel
