### ISSUE TITLE
Need Owners

### ISSUE THREAD

**Issue by stefangimmillaro** [Professor-Redwood-Team/Professor-Redwood#48]
I started a new job a couple months back which led to me abandoning both the game and the bot. @pjlangsam seems mostly out of commission too with the bot so I need to give this project more owners.

@kniteshift ?
@awilbur ?

**Comment by kniteshift** [comment]
@stefangimmillaro i will do it!

**Comment by stefangimmillaro** [comment]
@kniteshift I have invited you to the Professor-Redwood-Team
