### ISSUE TITLE
Reporting evolved pokemon in the wild - add additional !want notification as a stopgap

### ISSUE THREAD

**Issue by adorableducky** [Professor-Redwood-Team/Professor-Redwood#56]
Originally we talked about "candy families" so that reporting a blissey would alert users who subscribed to !want chansey.  This would avoid having to create separate roles for every evolution.   

In the meantime before that happens, can we add blissey to the bot so users can subscribe to !want ? This is the most common final evolution requested.

Thanks!

**Comment by kniteshift** [comment]
@adorableducky we can include this in the next push when we move to a DB driven system
